### ISSUE TITLE
Не работает админ панель после обновления PAGES - модуля

### ISSUE THREAD

**Issue by mirkoles** [studio107/Pages#8]
После обновления при переходе в админ панель ловим Exception:
```
Не определено свойство \"Modules\\Pages\\PagesModule.pagesForm\".
```
Пока откатился на старый commit все работает.

**Comment by max107** [comment]
Добрый день. Это в связи с затянувшимся рефакторингом модуля. Вообще обновление до HEAD - определенный риск =)

Попробуйте https://github.com/studio107/Pages/releases/tag/2.0 но из modules.php нужно будет удалить лишние переменные которые описаны в релизе. Если они у вас использовались, то нужно форкнуть модуль.
